name: Build NextJS

on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Nextjs
    steps:
         - uses: actions/checkout@v3
         - name: Build the Docker image
           run: docker build . -f Dockerfile.prod
