# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Nextjs
    steps:
         - uses: actions/checkout@v3
         - name: Build the Docker image
           run: docker build . -f Dockerfile.prod

  # This workflow contains a single job called "build"
  deploy_on_server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy On Server
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: SSH Remote Commands
          uses: appleboy/ssh-action@v0.1.4
          
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: |
              cd /home/ubuntu/pgps-backend
              python3 deploy.py --deploy frontend
